---
title: "03_analysis"
author: "Matheus Moroti"
format: html
editor: visual
---

### 0. Libraries

```{r}
library(vegan) # normalize dataset
library(picante) # prune sample with phy
library(tidyverse) # data science handling
library(phytools) # phylogenetic data
library(geiger) # phylogenetic plot
library(nlme) # gls analysis
library(cowplot) # plots
library(rr2) # r2 pgls
#library(modelsummary) # modelplots
```

### 1. Load data

#### 1.1. TetrapodTraits

```{r}
TetraData <- data.table::fread("../traits/TetrapodTraits_1.0.0.csv") %>%
  mutate(Scientific.Name = gsub(" ", "_", Scientific.Name)) %>%
  select(Scientific.Name, Fos, Ter, Aqu, Arb, Aer, ImputedHabitat) 
```

#### 1.2. Climate niche

```{r}
load(file.path(
  "..", "02_metrics", "omi_data", "niche_df.RData"
))
```

#### 1.3. Rate trait evolution

```{r}
# Amphibia
load(
  file.path("G:", "Meu Drive", "Artigos", "vertebrates_evolution", "Amphibia",
            "bodyrate_evolution.RData")
)
rate_body_amphibia <- Reduce(
  function(x, y) left_join(x, y, by = "specie"),
  lista_dfs
) %>%
  mutate(
    median_rate = apply(select(., starts_with("median_tree_")),
                        1, median, na.rm = TRUE)
  ) %>% select(specie, median_rate) %>%
  rename(taxa_fenotipica = median_rate)

# Reptilia
load(
  file.path("G:", "Meu Drive", "Artigos", "vertebrates_evolution", "Reptilia",
            "bodyrate_evolution.RData")
)
rate_body_reptilia <- Reduce(
  function(x, y) left_join(x, y, by = "specie"),
  lista_dfs
) %>%
  mutate(
    median_rate = apply(select(., starts_with("median_tree_")),
                        1, median, na.rm = TRUE)
  ) %>% select(specie, median_rate) %>%
  rename(taxa_fenotipica = median_rate)

# Birds
load(
  file.path("G:", "Meu Drive", "Artigos", "vertebrates_evolution", "Aves",
            "bodyrate_evolution.RData")
)
rate_body_birds <- Reduce(
  function(x, y) left_join(x, y, by = "specie"),
  lista_dfs
) %>%
  mutate(
    median_rate = apply(select(., starts_with("median_tree_")),
                        1, median, na.rm = TRUE)
  ) %>% select(specie, median_rate) %>%
  rename(taxa_fenotipica = median_rate)

# Mammals
load(
  file.path("G:", "Meu Drive", "Artigos", "vertebrates_evolution", "Mammalia",
            "bodyrate_evolution.RData")
)
rate_body_mammals <- Reduce(
  function(x, y) left_join(x, y, by = "specie"),
  lista_dfs
) %>%
  mutate(
    median_rate = apply(select(., starts_with("median_tree_")),
                        1, median, na.rm = TRUE)
  ) %>% select(specie, median_rate) %>%
  rename(taxa_fenotipica = median_rate)
```

#### 1.4. Phylogeny

```{r}
amphibia_phy_full <- read.tree(file.path(
  "G:", "Meu Drive", "Artigos", "vertebrates_evolution",
  "Amphibia", "Amphibia_Tree_1.tre"))

reptilia_phy_full <- read.tree(file.path(
  "G:", "Meu Drive", "Artigos", "vertebrates_evolution",
  "Reptilia", "Reptilia_Tree_1.tre"))

birds_phy_full <- read.tree(file.path(
  "G:", "Meu Drive", "Artigos", "vertebrates_evolution",
  "Aves", "Aves_Tree_1.tre"))

mammals_phy_full <- read.tree(file.path(
  "G:", "Meu Drive", "Artigos", "vertebrates_evolution",
  "Mammalia", "Mammalia_Tree_1.tre"))
```

### 2. Join data

#### 2.1. Amphibia

```{r}
niche_amphibia_df <- niche_amphibia_terrestrial_df %>%
  mutate(Scientific.Name = rownames(niche_amphibia_terrestrial_df)) %>%
  mutate(Scientific.Name = gsub(" ", "_", Scientific.Name)) %>%
  select(Scientific.Name, OMI, Tol)
```

Merge traits

```{r}
rate_niche_amphibia <- left_join(niche_amphibia_df,
          rate_body_amphibia,
          by = c("Scientific.Name" = "specie"))

df_trait_amphibia <- rate_niche_amphibia %>%
  left_join(TetraData, by = "Scientific.Name") 
```

Phylogeny to PGLS

```{r}
amphibia_community <- df_trait_amphibia %>%
  select(Scientific.Name, taxa_fenotipica) %>%
  pivot_wider(names_from = Scientific.Name, values_from = taxa_fenotipica)

amphibia_phy <- picante::prune.sample(amphibia_community,
                              amphibia_phy_full)
```

#### 1.2. Squamata

```{r}
niche_reptilia_df <- niche_reptilia_terrestrial_df %>%
  mutate(Scientific.Name = rownames(niche_reptilia_terrestrial_df)) %>%
  mutate(Scientific.Name = gsub(" ", "_", Scientific.Name)) %>%
  select(Scientific.Name, OMI, Tol)
```

Merge traits

```{r}
rate_niche_reptilia <- left_join(niche_reptilia_df,
          rate_body_reptilia,
          by = c("Scientific.Name" = "specie"))

df_trait_reptilia <- rate_niche_reptilia %>%
  left_join(TetraData, by = "Scientific.Name") 
```

Phylogeny to PGLS

```{r}
reptilia_community <- df_trait_reptilia %>%
  select(Scientific.Name, taxa_fenotipica) %>%
  pivot_wider(names_from = Scientific.Name, values_from = taxa_fenotipica)

reptilia_phy <- picante::prune.sample(reptilia_community,
                              reptilia_phy_full)
```

#### 1.3. Birds

```{r}
niche_birds_df <- niche_birds_terrestrial_df %>%
  mutate(Scientific.Name = rownames(niche_birds_terrestrial_df)) %>%
  mutate(Scientific.Name = gsub(" ", "_", Scientific.Name)) %>%
  select(Scientific.Name, OMI, Tol)
```

Merge traits

```{r}
rate_niche_birds <- left_join(niche_birds_df,
          rate_body_birds,
          by = c("Scientific.Name" = "specie"))

df_trait_birds <- rate_niche_birds %>%
  left_join(TetraData, by = "Scientific.Name") 
```

Phylogeny to PGLS

```{r}
birds_community <- df_trait_birds %>%
  select(Scientific.Name, taxa_fenotipica) %>%
  pivot_wider(names_from = Scientific.Name, values_from = taxa_fenotipica)

birds_phy <- picante::prune.sample(birds_community,
                              birds_phy_full)
```

#### 1.4. Mammals

```{r}
niche_mammals_df <- niche_mammals_terrestrial_df %>%
  mutate(Scientific.Name = rownames(niche_mammals_terrestrial_df)) %>%
  mutate(Scientific.Name = gsub(" ", "_", Scientific.Name)) %>%
  select(Scientific.Name, OMI, Tol)
```

Merge traits

```{r}
rate_niche_mammals <- left_join(niche_mammals_df,
          rate_body_mammals,
          by = c("Scientific.Name" = "specie"))

df_trait_mammals <- rate_niche_mammals %>%
  left_join(TetraData, by = "Scientific.Name") 
```

Phylogeny to PGLS

```{r}
mammals_community <- df_trait_mammals %>%
  select(Scientific.Name, taxa_fenotipica) %>%
  pivot_wider(names_from = Scientific.Name, values_from = taxa_fenotipica)

mammals_phy <- picante::prune.sample(mammals_community,
                              mammals_phy_full)
```

### 3. PGLS

#### 3.1. Amphibia

```{r}
# table(df_trait_amphibia$Aer) #0 nao entra
# binarizando as probabilidades de >0.5 para 1, e < para 0
df_trait_amphibia_bin <- df_trait_amphibia %>%
  mutate(across(
    .cols = c(Fos, Arb, Aqu, Ter),
    .fns  = ~ as.integer(.x > 0.5)
  ))
```

```{r}
# Os modelos melhoram ao transformar as variaveis
trait_amphibia_log <- df_trait_amphibia_bin %>%
  mutate(
    taxa_fenotipica = log(taxa_fenotipica),
    OMI    = log(OMI),
    Tol    = log(Tol+1),
    #taxa_tol   = log(taxa_tol),
    #taxa_omi = log(taxa_omi),
    Aqu    = as.integer(Aqu),
    Ter   = as.integer(Ter),
    Arb     = as.integer(Arb),
    Fos     = as.integer(Fos))

# Normalizando as preditoras
normalize_variables <- vegan::decostand(trait_amphibia_log %>%
                            select(OMI, Tol), #, taxa_tol
                          "normalize")

# Removendo as nao padronizadas e 
# e normalizando as preditoras
trait_amphibia_normalize <- cbind(trait_amphibia_log %>%
                               select(-OMI, -Tol),
                             normalize_variables)
```

```{r}
model_niche_amphibia <- gls(taxa_fenotipica ~ OMI + Tol +
                           Arb + Fos + Ter + Aqu,
                         data = trait_amphibia_normalize,
                    correlation = corPagel(1,amphibia_phy,
                                           form = ~Scientific.Name))

# Diagnose model
amphibia_diagnosis <- plot(model_niche_amphibia)

# AIC(model_niche_amphibia) # 15597 com log
AIC(df_trait_amphibia)

# Statistical model
summary(model_niche_amphibia)
R2(model_niche_amphibia)

save(model_niche_amphibia,
     file = "model_niche_amphibia_normalized.RData")

#load("model_niche_amphibia.RData")
```

#### 3.2. Squamata

```{r}
# binarizando as probabilidades de >0.5 para 1, e < para 0
df_trait_reptilia_bin <- df_trait_reptilia %>%
  mutate(across(
    .cols = c(Fos, Arb, Aqu, Ter),
    .fns  = ~ as.integer(.x > 0.5)
  ))
```

```{r}
# table(trait_reptilia_log$Aer) 0 nao entra

# Os modelos melhoram ao transformar as variaveis
trait_reptilia_log <- df_trait_reptilia_bin %>%
  mutate(
    taxa_fenotipica = log(taxa_fenotipica),
    OMI    = log(OMI),
    Tol    = log(Tol+1),
    #taxa_tol   = log(taxa_tol),
    #taxa_omi = log(taxa_omi),
    Aqu    = as.integer(Aqu),
    Ter   = as.integer(Ter),
    Arb     = as.integer(Arb),
    Fos     = as.integer(Fos))

# Normalizando as preditoras
normalize_variables <- vegan::decostand(trait_reptilia_log %>%
                            select(OMI, Tol), #, taxa_tol
                          "normalize")
# Removendo as nao padronizadas e 
# e normalizando as preditoras
trait_reptilia_normalize <- cbind(trait_reptilia_log %>%
                               select(-OMI, -Tol),
                             normalize_variables)
```

```{r}
model_niche_reptilia <- gls(taxa_fenotipica ~ OMI + Tol +
                           Arb + Fos + Ter + Aqu,
                         data = trait_reptilia_normalize,
                    correlation = corPagel(1,reptilia_phy,
                                           form = ~Scientific.Name))
# Model diagnose
reptilia_diagnosis <- plot(model_niche_reptilia)

# Statistical model
summary(model_niche_reptilia)
R2(model_niche_reptilia)

save(model_niche_reptilia,
     file = "model_niche_reptilia_normalize.RData")
```

#### 3.3. Birds

```{r}
#View(df_trait_birds)
# binarizando as probabilidades de >0.5 para 1, e < para 0
df_trait_birds_bin <- df_trait_birds %>%
  mutate(across(
    .cols = c(Arb, Aqu, Ter, Aer), # TODO CHECAR
    .fns  = ~ as.integer(.x > 0.5)
  ))
```

```{r}
# Os modelos melhoram ao transformar as variaveis
trait_birds_log <- df_trait_birds_bin %>%
  mutate(
    taxa_fenotipica = log(taxa_fenotipica),
    OMI    = log(OMI),
    Tol    = log(Tol+1),
    #taxa_tol   = log(taxa_tol),
    #taxa_omi = log(taxa_omi),
    Aqu    = as.integer(Aqu),
    Ter   = as.integer(Ter),
    Arb     = as.integer(Arb),
    Aer     = as.integer(Aer))

# Normalizando as preditoras
normalize_variables <- vegan::decostand(trait_birds_log %>%
                            select(OMI, Tol), #, taxa_tol
                          "normalize")
# Removendo as nao padronizadas e 
# e normalizando as preditoras
trait_birds_normalize <- cbind(trait_birds_log %>%
                               select(-OMI, -Tol),
                             normalize_variables)
```

```{r}
model_niche_birds <- gls(taxa_fenotipica ~ OMI + Tol +
                           Arb + Aer + Ter + Aqu,
                         data = trait_birds_normalize,
                    correlation = corPagel(1,birds_phy,
                                           form = ~Scientific.Name))

birds_diagnosis <- plot(model_niche_birds)# plot(resid(model_niche_birds) ~ fitted(model_niche_birds))
summary(model_niche_birds)
R2(model_niche_birds)

save(model_niche_birds,
     file = "model_niche_birds.RData")
```

#### 3.4. Mammals

```{r}
# binarizando as probabilidades de >0.5 para 1, e < para 0
df_trait_mammals_bin <- df_trait_mammals %>%
  mutate(across(
    .cols = c(Fos, Arb, Aqu, Ter, Aer), # TODO CHECAR
    .fns  = ~ as.integer(.x > 0.5)
  ))
```

```{r}
# Os modelos melhoram ao transformar as variaveis
trait_mammals_log <- df_trait_mammals_bin %>%
  mutate(
    taxa_fenotipica = log(taxa_fenotipica),
    OMI    = log(OMI),
    Tol    = log(Tol+1),
    #taxa_tol   = log(taxa_tol),
    #taxa_omi = log(taxa_omi),
    Aqu    = as.integer(Aqu),
    Ter   = as.integer(Ter),
    Arb     = as.integer(Arb),
    Fos     = as.integer(Fos),
    Aer = as.integer(Aer))

# Normalizando as preditoras
normalize_variables <- vegan::decostand(trait_mammals_log %>%
                            select(OMI, Tol), #, taxa_tol
                          "normalize")
# Removendo as nao padronizadas e 
# e normalizando as preditoras
trait_mammals_normalize <- cbind(trait_mammals_log %>%
                               select(-OMI, -Tol),
                             normalize_variables)
```

```{r}
model_niche_mammals <- gls(taxa_fenotipica ~ OMI + Tol + 
                             Aqu + Ter + Arb + Fos,
                         data = trait_mammals_log,
                    correlation = corPagel(1,mammals_phy,
                                           form = ~Scientific.Name))
# Diagnose model
mammals_diagnosis <- plot(model_niche_mammals)
# Model statistics 
summary(model_niche_mammals)
R2(model_niche_mammals)

save(model_niche_mammals,
     file = "model_niche_mammals.RData")
```

### 4.0 PWR

```{r}
library(pez)
library(phylobase)
library(MCMCglmm)
library(diversitree)
library(ib)

# EXEMPLO DO R
# Combine in phylobase format, and then run a scatterplot
c.data <- phylo4d(mammals_phy_pgls, mammals_dataset_full_normalizado)
c.data

plot(tipData(c.data)$Tol, tipData(c.data)$trait_rate, pch=rep(c(1,16), each=4),
     xlab="Predictor", ylab="Response", bty="l") +
  text(tipData(c.data)$Tol, tipData(c.data)$trait_rate,
       labels=rownames(tipData(c.data)),pos=3, cex=0.8)

# Phylogenetically weighted-regression with various weighting functions
pwr.b <- coef(pwr(trait_rate ~ Tol+OMI , c.data, wfun="brownian"))

pwr.m <- coef(pwr(y ~ x, combined.data, wfun="martins"))
pwr.g <- coef(pwr(y ~ x, combined.data, wfun="gaussian"))
pwr.G <- coef(pwr(y ~ x, combined.data, wfun="Gauss"))

# Run a PGLS
pgls <- gls(y ~ x, data=dat, correlation=corBrownian(phy=tree))

# Contrast the PWR and PGLS estimates
treePlot(addData(c.data, data.frame(gest=coef(mod_div_bw_prw)[2], glb=confint(mod_div_bw_prw)[2,1],
   gub=confint(mod_div_bw_prw)[2,2], phyloWR))[,c("est", "lb", "ub", "gest", "glb",
   "gub")], show.tip.label=TRUE, lower=-1., upper=1.5, pex=2, aex=3.5)
}

# Tue Jun 27 15:55:25 2023 ------------------------------
# aqui seguindo o script que o Diogo fez
mod_div_bw_prw <- gls(log(trait_rate)~Tol+OMI, data = mammals_dataset_full_normalizado,
                      correlation = corBrownian(phy=mammals_phy_pgls, form = ~Species))

phyloWR <- pwr(log(trait_rate)~Tol+OMI, c.data,
                      wfun="brownian", verbose=FALSE)

pwr.cv(log(trait_rate)~Tol+OMI, c.data, holdout = tipData(c.data), 
       coef = c("formula", "slope", "all"),model = c("pwr", "pgls"), wfun="brownian")

get.opt.bw(log(trait_rate)~Tol+OMI, c.data, wfun="martins", method="subplex")

bandw <- get.opt.bw(log(IR)~range,all_data, wfun="martins", method="subplex")

bandw#0.06224979

tp(addData(c.data, data.frame(gest=coef(mod_div_bw_prw)[2], glb=confint(mod_div_bw_prw)[2,1], gub=confint(mod_div_bw_prw)[2,2], phyloWR))[,c("est", "lb", "ub", "gest", "glb", "gub")], show.tip.label=TRUE, pex=2, aex=3.5)

# Tue Jun 27 16:27:55 2023 ------------------------------
all_data <- phylo4d(mammals_phy_pgls, mammals_dataset_full_normalizado)

mod_div_bw_prw <- gls(log(trait_rate)~Tol+OMI, data = mammals_dataset_full_normalizado,
                      correlation = corBrownian(phy=mammals_phy_pgls, form = ~Species))

phyloWR <- getEst(pwr(log(trait_rate)~Tol+OMI,all_data, wfun="brownian", verbose=FALSE))

bandw <- get.opt.bw(log(trait_rate)~Tol+OMI,all_data, wfun="martins", method="subplex")

bandw#0.06224979

tp(addData(all_data, data.frame(gest=coef(mod_div_bw_prw)[2], glb=confint(mod_div_bw_prw)[2,1], gub=confint(mod_div_bw_prw)[2,2], phyloWR))[,c("est", "lb", "ub", "gest", "glb", "gub")], show.tip.label=TRUE, pex=2, aex=3.5)
```

### 5.0. Plots

#### 5.1. Plot PCA Climatic niche

```{r}
# Load pca
load(
  "../02_metrics/omi_data/niche_pca.RData"
)

# Function to plot PCA
plot_pca <- function(pca_obj, title = NULL) {
  # Extrair dados dos indivíduos
  ind <- as.data.frame(pca_obj$li)
  ind$ID <- rownames(ind)
  
  # Extrair dados das variáveis
  var <- as.data.frame(pca_obj$co)
  var$varname <- rownames(var)
  
  # Verificar nomes das colunas (para adaptação a diferentes objetos PCA)
  axis1_name <- ifelse("Comp1" %in% colnames(var), "Comp1", 
                       ifelse("Axis1" %in% colnames(var), "Axis1", colnames(var)[1]))
  axis2_name <- ifelse("Comp2" %in% colnames(var), "Comp2", 
                       ifelse("Axis2" %in% colnames(var), "Axis2", colnames(var)[2]))
  
  # Criar o plot
  p <- ggplot() +
    geom_point(data = ind, aes(x = Axis1, y = Axis2), color = "gray30", size = 2) +
    geom_segment(data = var, 
                 aes(x = 0, y = 0, 
                     xend = !!sym(axis1_name), 
                     yend = !!sym(axis2_name)),
                 arrow = arrow(length = unit(0.2, "cm")), color = "red") +
    geom_text(data = var, 
              aes(x = !!sym(axis1_name), 
                  y = !!sym(axis2_name), 
                  label = varname),
              color = "red", vjust = -0.5) +
    theme_minimal() +
    labs(x = "PCA Axis 1", y = "PCA Axis 2",
         title = title) +
    geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.5) +
    geom_vline(xintercept = 0, linetype = "dashed", alpha = 0.5)
  
  return(p)
}

amphibia_pca <- plot_pca(dudi_amphibia_terrestre)
reptilia_pca <- plot_pca(dudi_reptilia_terrestre)
birds_pca <- plot_pca(dudi_birds_terrestre)
mammals_pca <- plot_pca(dudi_mammals_terrestre)

cowplot::plot_grid(amphibia_pca, reptilia_pca,
                   birds_pca, mammals_pca)
```

#### 5.2. Phylogeny plots
```{r}
library(phytools)

plot_trait_phylo <- function(df, tree) {
  # Ajusta nomes das linhas
  rownames(df) <- df$Scientific.Name
  # Checa nomes entre arvore e dados
  chk <- geiger::name.check(tree, df)
  # Define vetor com o trait
  ln.hosts <- setNames(df$trait, rownames(df))
  host.map <- contMap(tree, ln.hosts, plot = FALSE)
  # Aplica a paleta de cores
  host.map <- setMap(host.map, viridisLite::viridis(n = 8))
  # Plota sem legenda
  plot_result <- plot(host.map,
       fsize = c(1.2, 1.2),
       legend = FALSE,
       dig = 2,
       outline = FALSE,
       ftype = "off",
       type = "fan",
       lwd = c(2, 6))
  
  return(invisible(host.map))
}

amphibia_tree <- plot_trait_phylo(trait_amphibia_log, amphibia_phy, "OMI")


library(ggtree)

trait_amphibia_log -> df

circ <- ggtree(amphibia_phy, layout = "circular")

tip_order <- amphibia_phy$tip.label

trait_amphibia_log_ordered <- trait_amphibia_log[tip_order, ]
rownames(trait_amphibia_log_ordered) <- amphibia_phy$tip.label

t <- trait_amphibia_log_ordered %>%
  mutate(taxa_fenotipica = scale(taxa_fenotipica),
         OMI = scale(OMI),
         Tol = scale(Tol)
         ) %>%
  select(taxa_fenotipica, OMI, Tol)

plot_amphibia <- gheatmap(circ, t, width=0.1) +
  scale_fill_viridis_c(option="A", name="continuous\nvalue")
```

```{r}
# plot phy-climate niche
# frogs
anura_phy_pgls

rownames(amphibia_dataset_full) <- amphibia_dataset_full[,1]

amphibia_dataset_full <- amphibia_dataset_full[,-1]
amphibia_dataset_full <- amphibia_dataset_full[,-3]

col_order <- c("OMI", "OMI_past", "Tol","Tol_past")
amphibia_dataset_full_v2 <- amphibia_dataset_full[, col_order]

phy_niche_anura <- phylo4d(anura_phy_pgls, amphibia_dataset_full_v2)

# plot
gridplot(phy_niche_anura,show.tip = TRUE,tip.cex = 0.9, tree.type = "fan")

barplot(phy_niche_anura, trait.bg.col = c("#F6CED8", "#F6CED8", "#CEF1CE", "#CEF9CE"), 
        tree.type = "fan", bar.col = "grey35")

# squamata
squamata_phy_pgls

rownames(squamata_dataset_full) <- squamata_dataset_full[,1]

squamata_dataset_full <- squamata_dataset_full[,-1]
squamata_dataset_full <- squamata_dataset_full[,-3]

col_order <- c("OMI", "OMI_past", "Tol","Tol_past")
squamata_dataset_full_v2 <- squamata_dataset_full[, col_order]

phy_niche_squamata <- phylo4d(squamata_phy_pgls, squamata_dataset_full_v2)

# plot
gridplot(phy_niche_squamata,show.tip = TRUE,tip.cex = 0.9, tree.type = "fan")

barplot(phy_niche_squamata, trait.bg.col = c("#F6CED8", "#F6CED8", "#CEF1CE", "#CEF9CE"), 
        tree.type = "fan", bar.col = "grey35")

# birds
birds_phy_pgls

rownames(birds_dataset_full) <- birds_dataset_full[,1]

birds_dataset_full <- birds_dataset_full[,-1]
birds_dataset_full <- birds_dataset_full[,-3]

col_order <- c("OMI", "OMI_past", "Tol","Tol_past")
birds_dataset_full_v2 <- birds_dataset_full[, col_order]

phy_niche_birds <- phylo4d(birds_phy_pgls, birds_dataset_full_v2)

# plot
gridplot(phy_niche_birds,show.tip = TRUE,tip.cex = 0.9, tree.type = "fan")

barplot(phy_niche_anura, trait.bg.col = c("#F6CED8", "#F6CED8", "#CEF1CE", "#CEF9CE"), 
        tree.type = "fan", bar.col = "grey35")


# mammals
mammals_phy_pgls

rownames(mammals_dataset_full) <- mammals_dataset_full[,1]
mammals_dataset_full <- mammals_dataset_full[,-1]
mammals_dataset_full <- mammals_dataset_full[,-3]

col_order <- c("OMI", "OMI_past", "Tol","Tol_past")
my_data2 <- mammals_dataset_full[, col_order]

phy_niche <- phylo4d(mammals_phy_pgls, my_data2)

# plot
gridplot(phy_niche,show.tip = TRUE,tip.cex = 0.9, tree.type = "fan")

barplot(phy_niche, trait.bg.col = c("#F6CED8", "#F6CED8", "#CEF1CE", "#CEF9CE"), 
        tree.type = "fan", bar.col = "grey35")
gridplot(phy_niche)
```

#### 5.3. Model plots
```{r}
load(
  "model_niche_amphibia_log.RData"
)
load(
  "model_niche_reptilia_log.RData"
)
load(
  "model_niche_birds_log.RData"
)
load(
  "model_niche_mammals.RData"
)


summary(model_niche_amphibia)
summary(model_niche_reptilia)
summary(model_niche_birds)
summary(model_niche_mammals)

models <- list(Amphibia = model_niche_amphibia,
               Squamates = model_niche_reptilia,
               Birds = model_niche_birds, 
               Mammals = model_niche_mammals)

results <- modelsummary::modelplot(models, coef_omit = "Interc", draw=FALSE)

results$term <- factor(results$term, 
                       levels = c("OMI", "Tol", "Arb", 
                                  "Fos",
                                  "Ter","Aqu",
                                  "Aer"),
                       labels = c("Niche position\n(OMI)" ,"Niche breadth\n(Tol)", "Arboreal", 
                                  "Fossorial",
                                  "Terrestrial","Aquatic", 
                                  "Aerial"))

background_data <- data.frame(
  model = unique(results$model),  # agora a coluna se chama 'model'
  fill = c("#bfbbbc", "#bfbbbc", "#bfbbbc", "#bfbbbc")
)

p <- ggplot(results, aes(x = 1, y = estimate, ymin = conf.low, ymax = conf.high)) +
  geom_rect(data = background_data, 
            aes(xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf, fill = fill),
            inherit.aes = FALSE, show.legend = FALSE, alpha = 0.1) +
  geom_pointrange(shape = 21, size = 0.5, fill = "#bfbbbc", color = "black") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(x = NULL, y = "Model Coefficients (CI 95%)") +
  facet_grid(term ~ model, scales = "free_x", switch = "y") +
  coord_flip() +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    panel.background = element_blank(),
    axis.title = element_text(size = 10, face = "bold"),
    axis.text = element_text(size = 12),
    axis.line = element_line(colour = "black"),
    axis.ticks.y.left = element_blank(),
    axis.text.x = element_text(),
    axis.text.y = element_blank(),
    plot.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    strip.placement = "outside",
    strip.text.y.left = element_text(angle = 0, hjust = 1, vjust = 0.5, size = 12),
    legend.background = element_rect(colour = 'white', fill = 'white'),
    legend.key = element_blank(),
    legend.title = element_blank(),
    legend.position = "top") +
  scale_fill_identity() 

ggsave(paste0("../figures/fig4coefplot.tiff"), plot=p,
       width=10, height=6, units="in", dpi = 'print')
```
